### ISSUE TITLE
Unable to install securetea using PyPI

### ISSUE THREAD

**Issue by jishnurippon** [OWASP/SecureTea-Project#228]
**About the bug**
Unable to install securetea using 'pip install securetea' for new users.

**Steps**
1. Run 'pip install securetea' in the terminal.
2. it will show 
* Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4j0Q9Q/securetea/
* IOError: [Errno 2] No such file or directory: 'bin/init.d/securetea.sample'

**Screenshots**
![Screenshot from 2019-08-15 20-46-08 (1)](https://user-images.githubusercontent.com/48761358/63106712-14bbc280-bfa1-11e9-875c-07752c811c91.png)

**Desktop**
 - Operating System: Ubuntu
 - OS version: 18.04.3 LTS

**Detailed log**
```
Complete output from command python setup.py egg_info:
    [!] /usr/local/bin
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7tGccb/securetea/setup.py", line 219, in <module>
        file_rename()
      File "/tmp/pip-build-7tGccb/securetea/setup.py", line 80, in file_rename
        with open(file) as f:
    IOError: [Errno 2] No such file or directory: 'bin/init.d/securetea.sample'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7tGccb/securetea/
```

**Comment by abhisharma404** [comment]
Could you try: `sudo python3 -m pip install securetea`

**Comment by abhisharma404** [comment]
@jishnurippon Also, our initial PyPI release had some bugs which have been fixed now, it will be updated very soon in our next release. To install using the latest repo, please follow the following steps in order:
```
git clone https://github.com/OWASP/SecureTea-Project.git
cd SecureTea-Project
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py install
```

**Comment by rejahrehim** [comment]
@abhisharma404 Can we roll the fixes for the pip version? May be many will be trying to install with pip.

**Comment by abhisharma404** [comment]
@rejahrehim Yes, the fixes have been made. We can plan a release very soon. Also, I had a closer look at the error and tried to reproduce it in a VM, turns out this error is specifically due to 2 reasons:
1. Not using root, i.e. 'sudo'
2. Also, we need to enforce a Python 3.

The following command will work flawless:
`sudo python3 -m pip install securetea`

Also, #229 This error is also related to Python 2. I think we can have a discussion in the IRC related to the support of Python 2 & 3.

**Comment by jishnurippon** [comment]
**This error still exists.**
When I try on python 2.7 it will show.
![Screenshot from 2019-08-18 01-02-41](https://user-images.githubusercontent.com/48761358/63212728-6477c680-c126-11e9-8fa7-8063caf4b9b2.png)

**Comment by abhisharma404** [comment]
@jishnurippon What about Python 3?

**Comment by jishnurippon** [comment]
> @abhisharma404 python3 is working properly

**Comment by abhisharma404** [comment]
@jishnurippon Thanks for bringing this in attention. I'll try to work around it.. PyPi support over Python 2 needs a lot of work.
